### Send Channel Message
POST http://localhost:5000/message-api/channel-message
Content-Type: application/json

{
  "workspace": "69fabe65ee0e8df73ddaf3dc",
  "channel": "69fac00bee0e8df73ddaf3f0",
  "content": "Hello team, this is our first channel message"
}


### Get Channel Messages
GET http://localhost:5000/message-api/channel-messages/69fac00bee0e8df73ddaf3f0


### Send Direct Message
POST http://localhost:5000/message-api/direct-message
Content-Type: application/json

{
  "workspace": "69fabe65ee0e8df73ddaf3dc",
  "receiver": "69f8cd83bf5754b4922b85df",
  "content": "Hello, this is a direct message"
}


### Get Workspace Users For Direct Message
GET http://localhost:5000/dm-api/users/69fabe65ee0e8df73ddaf3dc


### Get Direct Messages With User
GET http://localhost:5000/dm-api/messages/69fabe65ee0e8df73ddaf3dc/69f8cd83bf5754b4922b85df


### Get Direct Message Conversations
GET http://localhost:5000/dm-api/conversations/69fabe65ee0e8df73ddaf3dc


### Send Channel Message With Priority And Reminder
POST http://localhost:5000/message-api/channel-message
Content-Type: application/json

{
  "workspace": "69fabe65ee0e8df73ddaf3dc",
  "channel": "69fac00bee0e8df73ddaf3f0",
  "content": "We must complete the frontend tomorrow before the meeting",
  "priority": "HIGH",
  "reminderTime": "2026-05-06T10:00:00.000Z"
}


### Send Direct Message With Priority And Reminder
POST http://localhost:5000/message-api/direct-message
Content-Type: application/json

{
  "workspace": "69fabe65ee0e8df73ddaf3dc",
  "receiver": "69f8cd83bf5754b4922b85df",
  "content": "Please check the deadline document tomorrow",
  "priority": "MEDIUM",
  "reminderTime": "2026-05-06T10:00:00.000Z"
}

### Get My Upcoming Reminders
GET http://localhost:5000/message-api/reminders



### Send File Message
POST http://localhost:5000/message-api/file-message
Content-Type: multipart/form-data; boundary=ChatBoundary

--ChatBoundary
Content-Disposition: form-data; name="workspace"

69fabe65ee0e8df73ddaf3dc
--ChatBoundary
Content-Disposition: form-data; name="channel"

69fac00bee0e8df73ddaf3f0
--ChatBoundary
Content-Disposition: form-data; name="messageType"

CHANNEL
--ChatBoundary
Content-Disposition: form-data; name="content"

Shared a file
--ChatBoundary
Content-Disposition: form-data; name="file"; filename="sample.png"
Content-Type: image/png

< ./sample.png
--ChatBoundary--


### Edit Own Message
PUT http://localhost:5000/message-api/message
Content-Type: application/json

{
  "messageId": "69fac1c1ee0e8df73ddaf3fa",
  "content": "Updated message content"
}


### Add Or Update Reaction
PUT http://localhost:5000/message-api/message/reaction
Content-Type: application/json

{
  "messageId": "69fac1c1ee0e8df73ddaf3fa",
  "reaction": "like"
}


### Remove Reaction
PATCH http://localhost:5000/message-api/message/reaction
Content-Type: application/json

{
  "messageId": "69fac1c1ee0e8df73ddaf3fa"
}


### Add Thread Reply
PUT http://localhost:5000/message-api/message/thread
Content-Type: application/json

{
  "messageId": "69fac1c1ee0e8df73ddaf3fa",
  "content": "This is a thread reply"
}


### Get Thread Replies
GET http://localhost:5000/message-api/message/thread/69fac1c1ee0e8df73ddaf3fa


### Soft Delete Message
PATCH http://localhost:5000/message-api/message/status
Content-Type: application/json

{
  "messageId": "69fac1c1ee0e8df73ddaf3fa",
  "isMessageActive": false
}


### Restore Message
PATCH http://localhost:5000/message-api/message/status
Content-Type: application/json


{
  "messageId": "69fac1c1ee0e8df73ddaf3fa",
  "isMessageActive": true
}


### Get Notifications
GET http://localhost:5000/notification-api/notifications


### Mark One Notification As Read
PATCH http://localhost:5000/notification-api/notification/read
Content-Type: application/json

{
  "notificationId": "69f8d696bf5754b4922b860d"
}


### Mark All Notifications As Read
PATCH http://localhost:5000/notification-api/notifications/read

